on:
  - push
name: Test
jobs:
  readmeExample:
    name: "[TEST] README example"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - uses: ./
        id: get_launches
        with:
          api_endpoint: "https://api.spacex.land/graphql/"
          headers: '{ "some-header-key": "some-header-value" }'
          output: launches.json
          variables: '{ "limit": 5, "sort": "launch_date_utc" }'
          query: |
            query First5Launches($limit: Int, $sort: String) {
              launches(limit: $limit, sort: $sort) {
                mission_name
                mission_id
                rocket {
                  rocket_name
                  rocket {
                    company
                    name
                    mass {
                      kg
                    }
                  }
                }
                launch_site {
                  site_name
                }
                launch_date_utc
              }
            }
      - run: "echo 'get_launches data ${{ steps.get_launches.outputs.data }}'"
      - run: "echo First Mission: `echo '${{ steps.get_launches.outputs.data }}' | jq -r '.launches[0].mission_name'`"
      - run: "echo 'Contents of launches.json' && cat launches.json"
